// Package sweepplan generates the default context/concurrency sweep grid
// with contract-compliant shapes and declared context semantics, per
// docs/2026-07-02-default-inference-sweep.md and
// docs/2026-07-02-context-semantics.md. Agents and users should generate
// sweeps here instead of hand-authoring the grid; generated specs must
// round-trip ValidateSpec with zero issues, which is enforced by test and by
// Plan itself.
package sweepplan

import (
	"fmt"
	"strings"

	"github.com/dutifuldev/localperf/internal/vllmbench"
)

type PlanRequest struct {
	// Model is the model identifier to benchmark (required).
	Model string
	// Contexts is the active-context ladder in tokens, e.g. 8192..131072.
	Contexts []int
	// Concurrency levels per point, e.g. 1,4,8,16,32.
	Concurrency []int
	// Repeats per measurement; defaults to 1.
	Repeats int
	// NumPrompts per measurement; defaults to 32.
	NumPrompts int
	// IncludeReference adds the 4k max-throughput-reference capacity family.
	IncludeReference bool
	// MinMemAvailableGiB is the safety memory floor; defaults to 40.
	MinMemAvailableGiB float64
	// BasePort is the first server port; defaults to 8100.
	BasePort int
}

const (
	defaultNumPrompts   = 32
	defaultMemFloorGiB  = 40
	defaultBasePort     = 8100
	referenceContext    = 4096
	decodeOutputCap     = 4096
	prefillOutputTokens = 1
)

// headroom absorbs chat template and tokenizer drift between requested and
// measured token counts; shapes land at roughly 98% of the target, well
// inside the 90% contract floor.
func headroom(context int) int {
	if context/64 > 64 {
		return context / 64
	}
	return 64
}

// PrefillShape returns input/output lengths for an active prefill point:
// minimal output so the run measures prefill through TTFT, not decode.
func PrefillShape(context int) (inputLen, outputLen int) {
	return context - headroom(context) - prefillOutputTokens, prefillOutputTokens
}

// DecodeShape returns input/output lengths for an active decode point: long
// prompt plus long output within the target.
func DecodeShape(context int) (inputLen, outputLen int) {
	outputLen = context / 4
	if outputLen > decodeOutputCap {
		outputLen = decodeOutputCap
	}
	return context - outputLen - headroom(context), outputLen
}

// Plan generates a validated sweep spec. Every workload carries a declared
// context claim: ladder points are active-context claims, the reference
// family is a capacity claim.
func Plan(request PlanRequest) (vllmbench.Spec, error) {
	if strings.TrimSpace(request.Model) == "" {
		return vllmbench.Spec{}, fmt.Errorf("model is required")
	}
	if len(request.Contexts) == 0 && !request.IncludeReference {
		return vllmbench.Spec{}, fmt.Errorf("at least one context point or the reference family is required")
	}
	if len(request.Concurrency) == 0 {
		request.Concurrency = []int{1, 4, 8, 16, 32}
	}
	if request.NumPrompts <= 0 {
		request.NumPrompts = defaultNumPrompts
	}
	if request.MinMemAvailableGiB <= 0 {
		request.MinMemAvailableGiB = defaultMemFloorGiB
	}
	if request.BasePort <= 0 {
		request.BasePort = defaultBasePort
	}

	warmupSeed := 0
	spec := vllmbench.Spec{
		Version:     "1",
		Name:        fmt.Sprintf("%s-default-sweep", vllmbench.Slug(request.Model)),
		Description: "Default context/concurrency sweep generated by localperf sweep plan.",
		Model:       request.Model,
		Safety:      vllmbench.SafetyConfig{MinMemAvailableGiB: request.MinMemAvailableGiB},
		Warmup: vllmbench.WarmupConfig{
			Enabled:        true,
			NumPrompts:     4,
			MaxConcurrency: 1,
			BenchmarkTrafficConfig: vllmbench.BenchmarkTrafficConfig{
				DatasetName:      "random",
				Seed:             &warmupSeed,
				RandomInputLen:   256,
				RandomOutputLen:  16,
				RandomRangeRatio: "0",
			},
		},
	}
	// The server must admit at least the highest requested concurrency.
	maxNumSeqs := 0
	for _, concurrency := range request.Concurrency {
		if concurrency > maxNumSeqs {
			maxNumSeqs = concurrency
		}
	}
	port := request.BasePort
	if request.IncludeReference {
		spec.Profiles = append(spec.Profiles, sweepProfile("4k-reference", referenceContext, port, maxNumSeqs))
		port++
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			"max-throughput-reference", "decode", "4k-reference",
			referenceContext, vllmbench.ContextSemanticsCapacity,
			1024, 1024, request))
	}
	for _, context := range request.Contexts {
		label := vllmbench.TokenCountLabel(context)
		spec.Profiles = append(spec.Profiles, sweepProfile(label, context, port, maxNumSeqs))
		port++
		prefillInput, prefillOutput := PrefillShape(context)
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			fmt.Sprintf("prefill-%s", label), "prefill", label,
			context, vllmbench.ContextSemanticsActive,
			prefillInput, prefillOutput, request))
		decodeInput, decodeOutput := DecodeShape(context)
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			fmt.Sprintf("decode-%s", label), "decode", label,
			context, vllmbench.ContextSemanticsActive,
			decodeInput, decodeOutput, request))
	}

	// Emit the normalized spec: explicit defaults are stable to diff and
	// leave nothing for a reader to guess.
	vllmbench.ApplyDefaults(&spec)
	if err := vllmbench.ValidateSpec(spec); err != nil {
		return vllmbench.Spec{}, fmt.Errorf("generated spec failed validation (generator/validator drift): %w", err)
	}
	return spec, nil
}

func sweepProfile(name string, maxModelLen, port, maxNumSeqs int) vllmbench.Profile {
	return vllmbench.Profile{
		Name:        name,
		Host:        "127.0.0.1",
		Port:        port,
		Managed:     true,
		MaxModelLen: maxModelLen,
		MaxNumSeqs:  maxNumSeqs,
	}
}

func sweepWorkload(name, phase, profile string, target int, semantics string, inputLen, outputLen int, request PlanRequest) vllmbench.Workload {
	seed := 0
	temperature := 0.0
	workload := vllmbench.Workload{
		Name:             name,
		Phase:            phase,
		Profiles:         []string{profile},
		ContextTarget:    target,
		ContextSemantics: semantics,
		BenchmarkTrafficConfig: vllmbench.BenchmarkTrafficConfig{
			Backend:          "openai-chat",
			DatasetName:      "random",
			Seed:             &seed,
			RandomInputLen:   inputLen,
			RandomOutputLen:  outputLen,
			RandomRangeRatio: "0",
			RequestRate:      "inf",
		},
		NumPrompts:     request.NumPrompts,
		MaxConcurrency: append([]int{}, request.Concurrency...),
		IgnoreEOS:      true,
		Temperature:    &temperature,
	}
	if request.Repeats > 0 {
		workload.Repeats = request.Repeats
	}
	return workload
}
