// Package sweepplan generates the default context/concurrency sweep grid
// with contract-compliant shapes and declared context semantics, per
// docs/2026-07-02-default-inference-sweep.md and
// docs/2026-07-02-context-semantics.md. Agents and users should generate
// sweeps here instead of hand-authoring the grid; generated specs must
// round-trip ValidateSpec with zero issues, which is enforced by test and by
// Plan itself.
package sweepplan

import (
	"fmt"
	"strings"

	"github.com/dutifuldev/localperf/internal/vllmbench"
)

type PlanRequest struct {
	// Model is the model identifier to benchmark (required).
	Model string
	// Contexts is the active-context ladder in tokens, e.g. 8192..131072.
	Contexts []int
	// Concurrency levels per point, e.g. 1,4,8,16,32.
	Concurrency []int
	// Repeats per measurement; defaults to 1.
	Repeats int
	// NumPrompts fixes the request count per measurement; when 0, prompts
	// scale with concurrency via PromptsPerUser instead.
	NumPrompts int
	// PromptsPerUser scales requests with concurrency
	// (num_prompts = max(8, PromptsPerUser * concurrency)); defaults to 2.
	PromptsPerUser int
	// IncludeReference adds the 4k max-throughput-reference capacity family.
	IncludeReference bool
	// IncludeStress adds long-output decode spot checks (4096 tokens at
	// 32k c4 and 64k c1/c4 when those contexts are in the ladder) and the
	// 128k points at c1/c4.
	IncludeStress bool
	// MinMemAvailableGiB is the safety memory floor; defaults to 40.
	MinMemAvailableGiB float64
	// BasePort is the first server port; defaults to 8100.
	BasePort int
}

const (
	defaultPromptsPerUser = 2
	defaultMemFloorGiB    = 40
	defaultBasePort       = 8100
	referenceContext      = 4096
	decodeOutputTokens    = 1024
	stressOutputTokens    = 4096
	prefillOutputTokens   = 1
	stressContext         = 131072
	// highContextConcurrencyCap bounds contexts >= 128k to c1/c4: beyond
	// that the KV budget makes higher concurrency an hours-long stress
	// exercise, which belongs in --stress, not the default grid.
	highContextConcurrencyCap = 4
)

// headroom absorbs chat template and tokenizer drift between requested and
// measured token counts; shapes land at roughly 98% of the target, well
// inside the 90% contract floor.
func headroom(context int) int {
	if context/64 > 64 {
		return context / 64
	}
	return 64
}

// PrefillShape returns input/output lengths for an active prefill point:
// minimal output so the run measures prefill through TTFT, not decode.
func PrefillShape(context int) (inputLen, outputLen int) {
	return context - headroom(context) - prefillOutputTokens, prefillOutputTokens
}

// DecodeShape returns input/output lengths for an active decode point: long
// prompt plus 1024 generated tokens. That is still hundreds of steady-state
// decode steps, and the shorter output keeps the measured active range close
// to the target; 4096-token outputs are the --stress preset's job.
func DecodeShape(context int) (inputLen, outputLen int) {
	return decodeShapeWithOutput(context, decodeOutputTokens)
}

// StressDecodeShape is the long-output variant used by stress spot checks.
func StressDecodeShape(context int) (inputLen, outputLen int) {
	return decodeShapeWithOutput(context, stressOutputTokens)
}

func decodeShapeWithOutput(context, output int) (inputLen, outputLen int) {
	if output > context/4 {
		output = context / 4
	}
	return context - output - headroom(context), output
}

// Plan generates a validated sweep spec. Every workload carries a declared
// context claim: ladder points are active-context claims, the reference
// family is a capacity claim.
func Plan(request PlanRequest) (vllmbench.Spec, error) {
	if strings.TrimSpace(request.Model) == "" {
		return vllmbench.Spec{}, fmt.Errorf("model is required")
	}
	if len(request.Contexts) == 0 && !request.IncludeReference {
		return vllmbench.Spec{}, fmt.Errorf("at least one context point or the reference family is required")
	}
	if len(request.Concurrency) == 0 {
		request.Concurrency = []int{1, 4, 8, 16, 32}
	}
	if request.NumPrompts <= 0 && request.PromptsPerUser <= 0 {
		request.PromptsPerUser = defaultPromptsPerUser
	}
	if request.MinMemAvailableGiB <= 0 {
		request.MinMemAvailableGiB = defaultMemFloorGiB
	}
	if request.BasePort <= 0 {
		request.BasePort = defaultBasePort
	}

	warmupSeed := 0
	spec := vllmbench.Spec{
		Version:     "1",
		Name:        fmt.Sprintf("%s-default-sweep", vllmbench.Slug(request.Model)),
		Description: "Default context/concurrency sweep generated by localperf sweep plan.",
		Model:       request.Model,
		Safety:      vllmbench.SafetyConfig{MinMemAvailableGiB: request.MinMemAvailableGiB},
		Warmup: vllmbench.WarmupConfig{
			Enabled:        true,
			NumPrompts:     4,
			MaxConcurrency: 1,
			BenchmarkTrafficConfig: vllmbench.BenchmarkTrafficConfig{
				DatasetName:      "random",
				Seed:             &warmupSeed,
				RandomInputLen:   256,
				RandomOutputLen:  16,
				RandomRangeRatio: "0",
			},
		},
	}
	// The server must admit at least the highest requested concurrency.
	maxNumSeqs := 0
	for _, concurrency := range request.Concurrency {
		if concurrency > maxNumSeqs {
			maxNumSeqs = concurrency
		}
	}
	port := request.BasePort
	if request.IncludeReference {
		spec.Profiles = append(spec.Profiles, sweepProfile("4k-reference", referenceContext, port, maxNumSeqs))
		port++
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			"max-throughput-reference", "decode", "4k-reference",
			referenceContext, vllmbench.ContextSemanticsCapacity,
			1024, 1024, request))
	}
	contexts := append([]int{}, request.Contexts...)
	if request.IncludeStress && !containsInt(contexts, stressContext) {
		contexts = append(contexts, stressContext)
	}
	for _, context := range contexts {
		label := vllmbench.TokenCountLabel(context)
		spec.Profiles = append(spec.Profiles, sweepProfile(label, context, port, maxNumSeqs))
		port++
		prefillInput, prefillOutput := PrefillShape(context)
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			fmt.Sprintf("prefill-%s", label), "prefill", label,
			context, vllmbench.ContextSemanticsActive,
			prefillInput, prefillOutput, request))
		decodeInput, decodeOutput := DecodeShape(context)
		spec.Workloads = append(spec.Workloads, sweepWorkload(
			fmt.Sprintf("decode-%s", label), "decode", label,
			context, vllmbench.ContextSemanticsActive,
			decodeInput, decodeOutput, request))
	}
	if request.IncludeStress {
		spec.Workloads = append(spec.Workloads, stressWorkloads(contexts, request)...)
	}

	// Emit the normalized spec: explicit defaults are stable to diff and
	// leave nothing for a reader to guess.
	vllmbench.ApplyDefaults(&spec)
	if err := vllmbench.ValidateSpec(spec); err != nil {
		return vllmbench.Spec{}, fmt.Errorf("generated spec failed validation (generator/validator drift): %w", err)
	}
	return spec, nil
}

func sweepProfile(name string, maxModelLen, port, maxNumSeqs int) vllmbench.Profile {
	return vllmbench.Profile{
		Name:        name,
		Host:        "127.0.0.1",
		Port:        port,
		Managed:     true,
		MaxModelLen: maxModelLen,
		MaxNumSeqs:  maxNumSeqs,
	}
}

// stressWorkloads adds long-output decode spot checks for ladder contexts
// that have them: 4096-token output at 32k c4 and 64k c1/c4. Kept out of the
// default grid because they dominate sweep wall time.
func stressWorkloads(contexts []int, request PlanRequest) []vllmbench.Workload {
	spots := []struct {
		context     int
		concurrency []int
	}{
		{32768, []int{4}},
		{65536, []int{1, 4}},
	}
	var workloads []vllmbench.Workload
	for _, spot := range spots {
		if !containsInt(contexts, spot.context) {
			continue
		}
		label := vllmbench.TokenCountLabel(spot.context)
		input, output := StressDecodeShape(spot.context)
		spotRequest := request
		spotRequest.Concurrency = spot.concurrency
		workloads = append(workloads, sweepWorkload(
			fmt.Sprintf("decode-stress-%s", label), "decode", label,
			spot.context, vllmbench.ContextSemanticsActive,
			input, output, spotRequest))
	}
	return workloads
}

func containsInt(values []int, wanted int) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

// pointConcurrency caps contexts >= 128k at c4; higher concurrency at those
// KV budgets is stress territory, not the default grid.
func pointConcurrency(context int, concurrency []int) []int {
	if context < stressContext {
		return append([]int{}, concurrency...)
	}
	capped := []int{}
	for _, value := range concurrency {
		if value <= highContextConcurrencyCap {
			capped = append(capped, value)
		}
	}
	if len(capped) == 0 {
		capped = []int{1}
	}
	return capped
}

func sweepWorkload(name, phase, profile string, target int, semantics string, inputLen, outputLen int, request PlanRequest) vllmbench.Workload {
	seed := 0
	temperature := 0.0
	workload := vllmbench.Workload{
		Name:             name,
		Phase:            phase,
		Profiles:         []string{profile},
		ContextTarget:    target,
		ContextSemantics: semantics,
		BenchmarkTrafficConfig: vllmbench.BenchmarkTrafficConfig{
			Backend:          "openai-chat",
			DatasetName:      "random",
			Seed:             &seed,
			RandomInputLen:   inputLen,
			RandomOutputLen:  outputLen,
			RandomRangeRatio: "0",
			RequestRate:      "inf",
		},
		NumPrompts:     request.NumPrompts,
		PromptsPerUser: request.PromptsPerUser,
		MaxConcurrency: pointConcurrency(target, request.Concurrency),
		IgnoreEOS:      true,
		Temperature:    &temperature,
	}
	if request.Repeats > 0 {
		workload.Repeats = request.Repeats
	}
	return workload
}
